### ISSUE TITLE
Feature: User can add income

### ISSUE THREAD

**Issue by Dustin-Davis** [Dustin-Davis/Finance-Tracker#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?
 

    User can add income 
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

  When a User clicks create a income will show up in entries 
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screenshot 2022-02-18 174817](https://user-images.githubusercontent.com/93169062/154781290-48a67cbe-e784-4fca-b70e-6f800ced519e.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.
  

- [x] create a folder for context 
- [x] create a file for context & contextReducer
- [x] set initialState to an empty array 
- [x] create context and set it initialState & assign it to a const 
- [x]  render full logic for provider 
- [x] import provider on index.js 
- [x] wrap App component with provider so we can use context 
- [x]  set up logic for contextReducer
- [x] set up useState hook 
- [x] set up select for type 
- [x] set up select for category 
- [x] set up select for amount 
- [x] set up select for date 
- [x] set up logic for the create button 
- [x] add transactions to list.jsx 

### 🧑‍⚕️ Clean Up
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
