### ISSUE TITLE
Feature: User can view the Finance Tracker

### ISSUE THREAD

**Issue by Dustin-Davis** [Dustin-Davis/Finance-Tracker#11]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

   User can view the finance tracker 
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The user will see the income tab the expense tab and the finance form.
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screenshot 2022-02-15 123504](https://user-images.githubusercontent.com/93169062/154144784-ca9d7156-547a-4985-b16b-43d331c869eb.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] create index.css in src folder
- [x] add a background 
- [x] create components folder inside src 
- [x] create a detail folder nested in components 
- [x] create a file named details for income & expense tab
- [x] import needed stuff 
- [x] create the detail structure 
- [x] create index.js for styles 
- [x] set up Grid 
- [x] set up styles.js for styling 
- [x]  add folder named main nested in src
- [x] create a file named main.jsx and create finance form 
- [x] set up styles for the form 
- [x] set up form structure   

### 🧑‍⚕️ Clean Up

- [x] ... 
- [x] ...
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
