### ISSUE TITLE
Feature: User can see list of entries

### ISSUE THREAD

**Issue by Dustin-Davis** [Dustin-Davis/Finance-Tracker#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

  User can see list of entries 
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

  User will see a list of the entries they have entered and be able to scroll through them 
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screenshot 2022-02-15 151309](https://user-images.githubusercontent.com/93169062/154165639-0743270d-add3-4200-b1b9-edf4b35c40d0.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x]  create a folder nested in main 
- [x] create a file for styles & list.jsx
- [x] import needed items 
- [x] map over all the transactions 
- [x] create list structure 

### 🧑‍⚕️ Clean Up

- [x] ... 
- [x] ...
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
